process_request:
  name: Process Request
  description: Send a natural language request to the Gemini Super Agent
  target:
    entity:
      domain: gemini_super_agent
  fields:
    text:
      name: Text
      description: The natural language request to process
      required: true
      example: "Create an automation that turns on the lights at sunset"
      selector:
        text:
    conversation_id:
      name: Conversation ID
      description: Identifier for the conversation thread
      default: "default"
      example: "living_room_automation"
      selector:
        text:
